=== denysdovhan/home-assistant-config/custom_components/powercalc/data/model_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "model.json described a light model",
  "type": "object",
  "required": [
    "name",
    "standby_power",
    "measure_method",
    "measure_device"
  ],
  "properties": {
    "name": {
      "type": "string",
      "description": "The full name"
    },
    "standby_power": {
      "type": "number",
      "minimum": 0.05,
      "description": "Power draw when the light is turned of. When you are not able to measure set to 0.4"
    },
    "standby_power_on": {
      "type": "number",
      "minimum": 0.05,
      "description": "Power draw when the light is turned on."
    },
    "supported_modes": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["lut", "linear", "fixed"]
      },
      "description": "Supported calculation modes"
    },
    "measure_method": {
      "type": "string",
      "enum": ["manual", "script"],
      "description": "How the light was measured"
    },
    "measure_device": {
      "type": "string",
      "description": "Device which was used to measure"
    },
    "measure_description": {
      "type": "string",
      "description": "Add more information about how you measured the light or any remarks"
    },
    "measure_settings": {
      "type": "object",
      "description": "Settings used for measure script"
    },
    "linked_lut": {
      "type": "string",
      "description": "Use LUT data files from another model"
    },
    "requires_additional_configuration": {
      "type": "boolean",
      "description": "Defines whether this model needs additional configuration by the user. Used for smart switches and lights where we can only know the standby power, but not the power of connected light bulb"
    },
    "device_type": {
      "type": "string",
      "enum": ["light", "smart_switch"],
      "description": "Type of device"
    },
    "calculation_enabled_condition": {
      "type": "string",
      "description": "Template which can be evaluated."
    },
    "linear_config": {
      "type": "object",
      "description": "Configuration for linear calculation mode",
      "properties": {
        "min_watt": {
          "type": "number"
        },
        "max_watt": {
          "type": "number"
        }
      }
    },
    "fixed_config": {
      "type": "object",
      "description": "Configuration for fixed calculation mode",
      "properties": {
        "watt": {
          "type": "number"
        }
      }
    }
  }
}

=== denysdovhan/home-assistant-config/custom_components/powercalc/data/rye/Candlebra/model.json
{
    "measure_description": "Measured with utils/measure script",
    "measure_device": "Anthom, Smart Plug",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 2,
        "SLEEP_TIME": 3,
        "VERSION": "master"
    },
    "name": "Candlebra",
    "standby_power": 0.4,
    "supported_modes": [
        "lut"
    ]
}

=== denysdovhan/home-assistant-config/custom_components/powercalc/data/ikea/LED2005R5/model.json
{
    "measure_description": "Measured with utils/measure script",
    "measure_device": "Shelly Plug S",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 3,
        "SLEEP_TIME": 6,
        "VERSION": "master"
    },
    "name": "TRADFRI LED bulb GU10 345 lumen, dimmable, white spectrum",
    "standby_power": 0.2,
    "supported_modes": [
        "lut"
    ]
}

=== denysdovhan/home-assistant-config/custom_components/powercalc/data/athom/rgbww-light/model.json
{
    "measure_description": "Measured with utils/measure script",
    "measure_device": "athom, smart-plug-v2",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 1,
        "SLEEP_TIME": 3,
        "VERSION": "master"
    },
    "name": "rgbww-light",
    "standby_power": 0.47,
    "supported_modes": [
        "lut"
    ]
}

=== denysdovhan/home-assistant-config/custom_components/powercalc/data/lifx/LIFX A19 Night Vision/model.json
{
    "measure_description": "Measured with utils/measure script. TP-link kp125 was having inconsistent readings towards the 0.52 watt and lower range, so I manually smoothed out some of the outliers",
    "measure_device": "TP-Link KP125",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 2,
        "SLEEP_TIME": 2,
        "VERSION": "v0.19.12:docker"
    },
    "name": "LIFX A19 Night Vision",
    "standby_power": 0.47,
    "supported_modes": [
        "lut"
    ]
}

=== denysdovhan/home-assistant-config/custom_components/powercalc/data/ikea/LED2002G5/model.json
{
    "measure_description": "Measured with utils/measure script",
    "measure_device": "Shelly, 1PM",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 1,
        "SLEEP_TIME": 2,
        "VERSION": "v0.13.4"
    },
    "name": "TRADFRIbulbE14WSglobeopal470lm",
    "standby_power": 0.23,
    "supported_modes": [
        "lut"
    ]
}

=== denysdovhan/home-assistant-config/custom_components/powercalc/data/signify/LST002/model.json
{
   "name":"Hue LightStrip Plus (2m)",
   "standby_power":0.18,
   "supported_modes":[
      "lut"
   ],
   "measure_device":"FRITZ!DECT 200",
   "measure_description":"Measured by custom script with all lightstrip extensions detached. Measured standby power with ELV Energy Master Profi 2",
   "measure_method":"script"
}

=== denysdovhan/home-assistant-config/custom_components/powercalc/data/ikea/LED1934G3/model.json
{
    "measure_description": "Measured with utils/measure script",
    "measure_device": "Shelly Plug S",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 2,
        "SLEEP_TIME": 3,
        "VERSION": "v0.22.1:docker"
    },
    "name": "TRADFRIbulbE27WWclear250lm",
    "standby_power": 0.27,
    "supported_modes": [
        "lut"
    ]
}
